import bcrypt from 'bcryptjs'
import { User } from './src/models/userModel'
import { Product } from './src/models/productModel'

export const sampleProducts: Product[] = [
  {
    name: 'Nike leather jacket',
    slug: 'nike-leather-jacket',
    category: 'Jacket',
    image: 'https://example.com/images/nike-leather-jacket.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality leather jacket',
  },
  {
    name: 'Adidas Fit fleece',
    slug: 'adidas-fit-fleece',
    category: 'Jacket',
    image: 'https://example.com/images/adidas-fit-fleece.jpg',
    price: 100,
    countInStock: 20,
    brand: 'Adidas',
    rating: 4.0,
    numReviews: 10,
    description: 'comfortable fleece jacket',
  },
  {
    name: 'Lacoste tops',
    slug: 'lacoste-tops',
    category: 'Tops',
    image: 'https://example.com/images/lacoste-tops.jpg',
    price: 220,
    countInStock: 0,
    brand: 'Lacoste',
    rating: 4.8,
    numReviews: 17,
    description: 'stylish Lacoste top',
  },
  {
    name: 'Nike tops',
    slug: 'nike-tops',
    category: 'Tops',
    image: 'https://example.com/images/nike-tops.jpg',
    price: 78,
    countInStock: 15,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 14,
    description: 'comfortable Nike top',
  },
  {
    name: 'Puma Running Shoes',
    slug: 'puma-running-shoes',
    category: 'Shoes',
    image: 'https://example.com/images/puma-running-shoes.jpg',
    price: 95,
    countInStock: 30,
    brand: 'Puma',
    rating: 4.2,
    numReviews: 20,
    description: 'lightweight running shoes',
  },
  {
    name: 'Levi\'s Denim Jeans',
    slug: 'levis-denim-jeans',
    category: 'Pants',
    image: 'https://example.com/images/levis-denim-jeans.jpg',
    price: 85,
    countInStock: 25,
    brand: 'Levi\'s',
    rating: 4.7,
    numReviews: 30,
    description: 'classic denim jeans',
  },
  {
    name: 'Under Armour Sports Bra',
    slug: 'under-armour-sports-bra',
    category: 'Underwear',
    image: 'https://example.com/images/under-armour-sports-bra.jpg',
    price: 35,
    countInStock: 40,
    brand: 'Under Armour',
    rating: 4.4,
    numReviews: 25,
    description: 'high-support sports bra',
  },
  {
    name: 'Ray-Ban Sunglasses',
    slug: 'ray-ban-sunglasses',
    category: 'Accessories',
    image: 'https://example.com/images/ray-ban-sunglasses.jpg',
    price: 150,
    countInStock: 12,
    brand: 'Ray-Ban',
    rating: 4.9,
    numReviews: 40,
    description: 'classic aviator sunglasses',
  },
  {
    name: 'The North Face Backpack',
    slug: 'north-face-backpack',
    category: 'Bags',
    image: 'https://example.com/images/north-face-backpack.jpg',
    price: 80,
    countInStock: 18,
    brand: 'The North Face',
    rating: 4.6,
    numReviews: 22,
    description: 'durable hiking backpack',
  },
  {
    name: 'Casio Digital Watch',
    slug: 'casio-digital-watch',
    category: 'Accessories',
    image: 'https://example.com/images/casio-digital-watch.jpg',
    price: 50,
    countInStock: 35,
    brand: 'Casio',
    rating: 4.3,
    numReviews: 15,
    description: 'water-resistant digital watch',
  }
]

export const sampleUsers: User[] = [
  {
    name: 'Joe',
    email: 'admin@example.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: true,
  },
  {
    name: 'John',
    email: 'user@example.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: false,
  },
]